# Generated by Django 5.1.1 on 2024-10-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlanMyAssignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grader_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_id", models.IntegerField()),
                ("part_name", models.CharField(max_length=255)),
                ("part_review", models.CharField(max_length=2000)),
                ("part_student_score", models.IntegerField()),
                ("part_score", models.IntegerField()),
                (
                    "grading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="PlanMyAssignment.grading",
                    ),
                ),
            ],
        ),
    ]
