# Generated by Django 5.1.1 on 2024-11-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanMyAssignment', '0002_grading_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='description',
            field=models.TextField(default='ss'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
